export const FETCH_SINGLE_PHOTO = "FETCH_SINGLE_PHOTO";
export const LOADING_SINGLE_PHOTO = "LOADING_SINGLE_PHOTO";
export const FETCH_SINGLE_PHOTO_LOADED = "FETCH_SINGLE_PHOTO_LOADED";
export const ERROR_SINGLE_PHOTO = "ERROR_SINGLE_PHOTO";
